#!/usr/bin/env ruby

ignore 'web'

#
# Run thin server to give site a spin.
#
desc "start thin server"
task "serve" do
  sh "thin start -A file"
end

#
# Compile Handlebar.js templates.
#
desc "compile templates"
task "compile" do
  sh "handlebars source/templates/*.handlebars -f assets/javascripts/handlebars.templates.js"
end

# compile templates
file 'source/templates/**/*' do
  run :compile
end

# Copy files to web directory.
task 'web:copy' do
  mkdir_p 'web'
  install 'index.html', 'web/index.html'
  install 'doc.json', 'web/doc.json'
  sync 'assets', 'web/assets'
end

# The publish task uses the detroit-github plugin
# from the Detroit project.
desc "publish to github"
task 'web:publish' => ['web:copy'] do
  github.publish
end

# Create web directory for gh-pages repo.
desc "prepare for github"
task "prepare" do
  github.prepare
end

#
def github
  @github ||= (
    require 'detroit'
    require 'detroit-github'
   
    Detroit::GitHub.new(
      :folder  => 'web'
      #:sitemap => {
      #  'index.html' => 'index.html',
      #  'doc.json'   => 'doc.json',
      #  'assets'     => 'assets'
      #}
    )
  ) 
end

